Main.twinPrimes(100).toArray()
Main.twinPrimes(100)
Main.twinPrimes(100).toArray()
Main.twinPrimes(100).count()
Main.twinPrimes(2).forEach(System.out::println)
Main.twinPrimes(2).count()
Main.twinPrimes(3).forEach(System.out::println)
